### PR TITLE
feat: added Snapchat button

### PR DESCRIPTION
**Pull request by angelxmoreno**
Here is the snack link preview: https://snack.expo.dev/@angelxmoreno/github.com-angelxmoreno-expo-snack-test

### CODE REVIEW

**Comment by angelxmoreno** [comment]
@dclipca come to think of it, it might be worthwhile creating a snack link to replace the image on the README. what do you think @dclipca ?

**Comment by dclipca** [comment]
> come to think of it, it might be worthwhile creating a snack link to replace the image on the README. what do you think @dclipca ?

What exactly is snack? Can't find anything about it

**Comment by dclipca** [comment]
Sorry, didn't see the link. This sounds good but how fast will the snack preview load? Might be too long. Maybe having both would make more sense?

**Comment by dclipca** [comment]
Btw feel free to merge on your own, you should be admin for the repo. At this point I'm not really devving much for React Native and I think you'll be a good maintainer.

**Comment by angelxmoreno** [comment]
👍

**Pull request merged**
